//
//  Constants.swift
//  Yamaha
//
//  Created by SmartVenture on 5/2/23.
//

import Foundation

struct Constants {
  
  // Mark: - API
  static let baseURL = "https://dev.lstr.app/"
  
  static let token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImI2NzE1ZTJmZjcxZDIyMjQ5ODk1MDAyMzY2ODMwNDc3Mjg2Nzg0ZTMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiVGVzdGVyIFplcm8iLCJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbHN0ci02NTJkNyIsImF1ZCI6ImxzdHItNjUyZDciLCJhdXRoX3RpbWUiOjE2ODM2MTgyNDAsInVzZXJfaWQiOiJIMDBJR2RLV2dIY0p5MmdLanVpdmI1cnNRV0YzIiwic3ViIjoiSDAwSUdkS1dnSGNKeTJnS2p1aXZiNXJzUVdGMyIsImlhdCI6MTY4MzYxODI0MCwiZXhwIjoxNjgzNjIxODQwLCJlbWFpbCI6ImludnJlZjFAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImludnJlZjFAZW1haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.CJH--4LQoTlGu5h-WF9SEIPBy8F5xib_aq5ujpTQFdJ6yVL9oIs0qoRemLc9eC2jNNy07x0ALkMTbASHWrS1T3tLnQlEZrefePksZXvcVkIMmzcYgxFXs3VaQn8KWVEM859VSyzDPCV3bsZhF4EctHzWd-TCLf2sYtt_mhQkNTjYU_xsc0uyhFhvI4-OaIZzYMX1ID2Xf_5PfBR4iByfemTDRKgoFnNvT4kq6Outp7rAg2qCDnpjYKUQvpjG38yr06AzU6eKJ5GgWk_QJdCcTZW5RMuwRBY-CbQ3WKP3VoYM3BMl5_OeYwz6f3hvf-wawft_VXvjWOiekuvyodKeUA"
}
